# Generated by Django 4.0.4 on 2022-05-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_forgot_password',
                                      to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'forgot_password',
                'verbose_name_plural': 'forgot_password',
            },
        ),
    ]
